export const CLIENT_ERROR_CODE = {
  NETWORK_UNAVAILABLE: 'NETWORK_UNAVAILABLE',
  ACK_TIMEOUT: 'ACK_TIMEOUT',
  SOCKET_DISCONNECTED: 'SOCKET_DISCONNECTED',
  PROTOCOL_MISMATCH: 'PROTOCOL_MISMATCH',
  INVALID_RESPONSE: 'INVALID_RESPONSE',
  SESSION_DISPOSED: 'SESSION_DISPOSED',
  STATE_UNAVAILABLE: 'STATE_UNAVAILABLE',
} as const;

export type ClientErrorCode = (typeof CLIENT_ERROR_CODE)[keyof typeof CLIENT_ERROR_CODE];

export type TransportErrorCode =
  | typeof CLIENT_ERROR_CODE.NETWORK_UNAVAILABLE
  | typeof CLIENT_ERROR_CODE.SOCKET_DISCONNECTED
  | typeof CLIENT_ERROR_CODE.ACK_TIMEOUT;

export type ProtocolErrorCode =
  | typeof CLIENT_ERROR_CODE.PROTOCOL_MISMATCH
  | typeof CLIENT_ERROR_CODE.INVALID_RESPONSE
  | typeof CLIENT_ERROR_CODE.SESSION_DISPOSED
  | typeof CLIENT_ERROR_CODE.STATE_UNAVAILABLE;
