import { PUBLIC_ERROR_CODE, type PublicErrorCode } from '@repo/game-protocol/errors';

const HTTP_STATUS_BY_PUBLIC_ERROR = {
  [PUBLIC_ERROR_CODE.INVALID_REQUEST]: 400,
  [PUBLIC_ERROR_CODE.PROTOCOL_MISMATCH]: 409,
  [PUBLIC_ERROR_CODE.ROOM_NOT_FOUND]: 404,
  [PUBLIC_ERROR_CODE.ROOM_NOT_JOINABLE]: 409,
  [PUBLIC_ERROR_CODE.ROOM_ALREADY_MATCHED]: 409,
  [PUBLIC_ERROR_CODE.ROOM_CODE_EXHAUSTED]: 503,
  [PUBLIC_ERROR_CODE.INVALID_AUTHORITY]: 403,
  [PUBLIC_ERROR_CODE.RESUME_NOT_AVAILABLE]: 409,
  [PUBLIC_ERROR_CODE.SESSION_REPLACED]: 409,
  [PUBLIC_ERROR_CODE.NOT_YOUR_TURN]: 409,
  [PUBLIC_ERROR_CODE.STALE_TURN]: 409,
  [PUBLIC_ERROR_CODE.TURN_EXPIRED]: 409,
  [PUBLIC_ERROR_CODE.TURN_NOT_STARTED]: 409,
  [PUBLIC_ERROR_CODE.ROLL_LIMIT_REACHED]: 409,
  [PUBLIC_ERROR_CODE.NO_DICE_TO_ROLL]: 409,
  [PUBLIC_ERROR_CODE.HOLD_NOT_ALLOWED]: 409,
  [PUBLIC_ERROR_CODE.CATEGORY_ALREADY_RECORDED]: 409,
  [PUBLIC_ERROR_CODE.INVALID_CATEGORY]: 400,
  [PUBLIC_ERROR_CODE.MATCH_FINISHED]: 409,
  [PUBLIC_ERROR_CODE.ACTION_ID_REUSED]: 409,
  [PUBLIC_ERROR_CODE.ACTION_RESULT_EXPIRED]: 409,
  [PUBLIC_ERROR_CODE.RATE_LIMITED]: 429,
  [PUBLIC_ERROR_CODE.ROLL_UNAVAILABLE]: 503,
  [PUBLIC_ERROR_CODE.INTERNAL_ERROR]: 500,
} satisfies Record<PublicErrorCode, number>;

export function httpStatusForPublicError(code: PublicErrorCode): number {
  return HTTP_STATUS_BY_PUBLIC_ERROR[code];
}
