import {
  createPublicError,
  PUBLIC_ERROR_CODE,
  type PublicError,
  type PublicErrorCode,
} from '@repo/game-protocol/errors';

import type { FailedRollCommandExecution } from '@/roll/roll-command-executor';
import type { CommitFailure } from '@/rooms/application/room-state-committer';
import { MATCH_REJECTION_CODE, type MatchRejectionCode } from '@/rooms/domain/match';
import { ROOM_REJECTION_CODE, type RoomRejectionCode } from '@/rooms/domain/room-constants';

const ROOM_REJECTION_TO_PUBLIC_ERROR = {
  [ROOM_REJECTION_CODE.INVALID_ROOM_CODE]: PUBLIC_ERROR_CODE.INVALID_REQUEST,
  [ROOM_REJECTION_CODE.INVALID_PROFILE]: PUBLIC_ERROR_CODE.INVALID_REQUEST,
  [ROOM_REJECTION_CODE.INVALID_TIMESTAMP]: PUBLIC_ERROR_CODE.INTERNAL_ERROR,
  [ROOM_REJECTION_CODE.ROOM_NOT_WAITING]: PUBLIC_ERROR_CODE.ROOM_NOT_JOINABLE,
  [ROOM_REJECTION_CODE.WAITING_ROOM_EXPIRED]: PUBLIC_ERROR_CODE.ROOM_NOT_JOINABLE,
  [ROOM_REJECTION_CODE.ROOM_NOT_PLAYING]: PUBLIC_ERROR_CODE.RESUME_NOT_AVAILABLE,
  [ROOM_REJECTION_CODE.ROOM_FINISHED]: PUBLIC_ERROR_CODE.MATCH_FINISHED,
  [ROOM_REJECTION_CODE.SEAT_NOT_FOUND]: PUBLIC_ERROR_CODE.INVALID_AUTHORITY,
  [ROOM_REJECTION_CODE.RECONNECT_NOT_AVAILABLE]: PUBLIC_ERROR_CODE.RESUME_NOT_AVAILABLE,
} satisfies Record<RoomRejectionCode, EmptyErrorCode>;

const MATCH_REJECTION_TO_PUBLIC_ERROR = {
  [MATCH_REJECTION_CODE.NOT_YOUR_TURN]: PUBLIC_ERROR_CODE.NOT_YOUR_TURN,
  [MATCH_REJECTION_CODE.STALE_TURN]: PUBLIC_ERROR_CODE.STALE_TURN,
  [MATCH_REJECTION_CODE.TURN_EXPIRED]: PUBLIC_ERROR_CODE.TURN_EXPIRED,
  [MATCH_REJECTION_CODE.TURN_NOT_STARTED]: PUBLIC_ERROR_CODE.TURN_NOT_STARTED,
  [MATCH_REJECTION_CODE.TURN_NOT_EXPIRED]: PUBLIC_ERROR_CODE.INVALID_REQUEST,
  [MATCH_REJECTION_CODE.ROLL_LIMIT_REACHED]: PUBLIC_ERROR_CODE.ROLL_LIMIT_REACHED,
  [MATCH_REJECTION_CODE.NO_DICE_TO_ROLL]: PUBLIC_ERROR_CODE.NO_DICE_TO_ROLL,
  [MATCH_REJECTION_CODE.HOLD_NOT_ALLOWED]: PUBLIC_ERROR_CODE.HOLD_NOT_ALLOWED,
  [MATCH_REJECTION_CODE.SCORE_NOT_ALLOWED]: PUBLIC_ERROR_CODE.INVALID_REQUEST,
  [MATCH_REJECTION_CODE.CATEGORY_ALREADY_RECORDED]: PUBLIC_ERROR_CODE.CATEGORY_ALREADY_RECORDED,
  [MATCH_REJECTION_CODE.INVALID_CATEGORY]: PUBLIC_ERROR_CODE.INVALID_CATEGORY,
  [MATCH_REJECTION_CODE.INVALID_PLAYER]: PUBLIC_ERROR_CODE.INVALID_AUTHORITY,
  [MATCH_REJECTION_CODE.MATCH_FINISHED]: PUBLIC_ERROR_CODE.MATCH_FINISHED,
} satisfies Record<MatchRejectionCode, EmptyErrorCode>;

type EmptyErrorCode = Exclude<PublicErrorCode, typeof PUBLIC_ERROR_CODE.RATE_LIMITED>;

export function mapRoomRejection(
  code: RoomRejectionCode,
): (typeof ROOM_REJECTION_TO_PUBLIC_ERROR)[RoomRejectionCode] {
  return ROOM_REJECTION_TO_PUBLIC_ERROR[code];
}

export function mapMatchRejection(
  code: MatchRejectionCode,
): (typeof MATCH_REJECTION_TO_PUBLIC_ERROR)[MatchRejectionCode] {
  return MATCH_REJECTION_TO_PUBLIC_ERROR[code];
}

export function mapRollFailure(reason: FailedRollCommandExecution['reason']): PublicError {
  return reason === 'capacity'
    ? createPublicError(PUBLIC_ERROR_CODE.RATE_LIMITED, { retryAfterMs: 1_000 })
    : createPublicError(PUBLIC_ERROR_CODE.ROLL_UNAVAILABLE, {});
}

export function mapCommitFailure(reason: CommitFailure['reason']): PublicError {
  return reason === 'ledgerCapacity'
    ? createPublicError(PUBLIC_ERROR_CODE.RATE_LIMITED, { retryAfterMs: 1_000 })
    : createPublicError(PUBLIC_ERROR_CODE.INTERNAL_ERROR, {});
}
